/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GovernanceFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "communities"
      | "communityCount"
      | "createCommunity"
      | "getSpaceAddress"
      | "spaceByIdStr"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CommunityCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "communities",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "communityCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCommunity",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpaceAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "spaceByIdStr",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "communities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "communityCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCommunity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSpaceAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spaceByIdStr",
    data: BytesLike
  ): Result;
}

export namespace CommunityCreatedEvent {
  export type InputTuple = [
    index: BigNumberish,
    spaceAddress: AddressLike,
    owner: AddressLike,
    communityId: string
  ];
  export type OutputTuple = [
    index: bigint,
    spaceAddress: string,
    owner: string,
    communityId: string
  ];
  export interface OutputObject {
    index: bigint;
    spaceAddress: string;
    owner: string;
    communityId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GovernanceFactory extends BaseContract {
  connect(runner?: ContractRunner | null): GovernanceFactory;
  waitForDeployment(): Promise<this>;

  interface: GovernanceFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  communities: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        spaceAddress: string;
        owner: string;
        communityId: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  communityCount: TypedContractMethod<[], [bigint], "view">;

  createCommunity: TypedContractMethod<
    [
      communityId: string,
      quorumPercent: BigNumberish,
      voteDurationSecs: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getSpaceAddress: TypedContractMethod<[communityId: string], [string], "view">;

  spaceByIdStr: TypedContractMethod<[arg0: string], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "communities"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        spaceAddress: string;
        owner: string;
        communityId: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "communityCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createCommunity"
  ): TypedContractMethod<
    [
      communityId: string,
      quorumPercent: BigNumberish,
      voteDurationSecs: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSpaceAddress"
  ): TypedContractMethod<[communityId: string], [string], "view">;
  getFunction(
    nameOrSignature: "spaceByIdStr"
  ): TypedContractMethod<[arg0: string], [string], "view">;

  getEvent(
    key: "CommunityCreated"
  ): TypedContractEvent<
    CommunityCreatedEvent.InputTuple,
    CommunityCreatedEvent.OutputTuple,
    CommunityCreatedEvent.OutputObject
  >;

  filters: {
    "CommunityCreated(uint256,address,address,string)": TypedContractEvent<
      CommunityCreatedEvent.InputTuple,
      CommunityCreatedEvent.OutputTuple,
      CommunityCreatedEvent.OutputObject
    >;
    CommunityCreated: TypedContractEvent<
      CommunityCreatedEvent.InputTuple,
      CommunityCreatedEvent.OutputTuple,
      CommunityCreatedEvent.OutputObject
    >;
  };
}
