/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernanceFactory } from "./GovernanceFactory";
export type { GovernanceSpace } from "./GovernanceSpace";
export * as factories from "./factories";
export { GovernanceFactory__factory } from "./factories/GovernanceFactory__factory";
export { GovernanceSpace__factory } from "./factories/GovernanceSpace__factory";
