/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernanceFactory__factory } from "./GovernanceFactory__factory";
export { GovernanceSpace__factory } from "./GovernanceSpace__factory";
